image: registry.gitlab.info.uqam.ca/inf31351/docker/base

stages:
  - build
  - test

build:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - bin/tempo

test-bats:
  stage: test
  script:
    - make test-bats

test-libtap:
  stage: test
  script:
    - make test-libtap
