image: registry.gitlab.info.uqam.ca/inf31351/docker/base

stages:
  - build
  - test

build:
  stage: build
  script:
    - apt install strace
    - make build || strace -f make build
  artifacts:
    paths:
      - bin/tempo

test:
  stage: test
  script:
    - make test || strace -f make test
