image: registry.gitlab.info.uqam.ca/inf31351/docker/base

before_script:
  - apt-get update -qq
  - apt-get install -y -qq libjansson-dev pkg-config gnuplot
  
stages:
  - build
  - test

build:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - bin/tempo

test-bats:
  stage: test
  script:
    - make test-bats

test-libtap:
  stage: test
  script:
    - make test-libtap
