.PHONY: count test

test: test_tempo test_describe test_show

test_tempo:
	bats-core/bin/bats test_tempo.bats

test_describe:
	bats-core/bin/bats test_describe.bats

test_show:
	bats-core/bin/bats test_show.bats
